version: "3.9"
services:
  api:
    build: .
    container_name: verocta_api
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: postgres:16
    container_name: verocta_db
    environment:
      POSTGRES_DB: verocta
      POSTGRES_USER: verocta
      POSTGRES_PASSWORD: verocta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: verocta_redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
